apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-relay-secret
  namespace: observability
type: Opaque
stringData:
  bearer-token: "9ef1aa003fbc327256fbfdf50dabf78496c7b3817dcf4687d0e4db3aaf7eae8c"
